# Generated by Django 3.1.6 on 2021-02-05 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions_and_points.payer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions_and_points.user')),
            ],
        ),
        migrations.AddField(
            model_name='payer',
            name='users',
            field=models.ManyToManyField(through='transactions_and_points.Transaction', to='transactions_and_points.User'),
        ),
    ]
