# Generated by Django 3.1.6 on 2021-02-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_and_points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='users',
            field=models.ManyToManyField(related_name='payers', through='transactions_and_points.Transaction', to='transactions_and_points.User'),
        ),
    ]
