# Generated by Django 3.1.6 on 2021-02-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_and_points', '0002_auto_20210208_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payer',
            new_name='payer_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='user_id',
        ),
    ]
